go2_bringup:
    - '[x] go2_bringup'
go2_description:
    - '[x] go2_description'
go2_driver:
    - '[ ] go2_driver'
go2_hardware:
    - 'go2_hardware'
go2_interfaces:
    - 'go2_interfaces'
go2_navigation:
    - 'go2_navigation'
go2_robot:
    - 'go2_robot'
go2_rviz:
    - 'go2_rviz'
go2_simulation:
    - 'go2_simulation'
go2_tts:
    - 'go2_tts'
go2_tts_interfaces:
    - 'go2_tts_interfaces'
go2_voxel_map:
    - 'go2_voxel_map'
unitree_api:
    - 'unitree_api'
unitree_go:
    - 'unitree_go'
