name: Label Issues Based on Checkboxes
on:
  issues:
    types: [opened, edited]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Get Issue Body and Extract Checkboxes
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || "";
            const labels = [];

            // Lista de paquetes válidos
            const package_labels = [
              "go2_bringup", "go2_description", "go2_driver", "go2_hardware",
              "go2_interfaces", "go2_navigation", "go2_robot", "go2_rviz",
              "go2_simulation", "go2_tts", "go2_tts_interfaces", "go2_voxel_map",
              "unitree_api", "unitree_go"
            ];

            // Expresión regular para encontrar los checkboxes marcados ([x] package_name)
            const checkboxRegex = /\[x\] (.+)/g;
            let match;

            while ((match = checkboxRegex.exec(body)) !== null) {
              const packageName = match[1].trim();
              if (package_labels.includes(packageName)) {
                labels.push(packageName);
              }
            }

            // Agregar etiquetas si hay paquetes seleccionados
            if (labels.length > 0) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labels
              });
            } else {
              console.log("No se encontraron checkboxes marcados.");
            }
