name: Print Issue Body
on:
  issues:
    types: [opened, edited]

jobs:
  print_issue:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Get Issue Body
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            console.log("🔹 Issue Title: " + issue.title);
            console.log("🔹 Issue Body:\n" + issue.body);
