name: main

on:
  push:
    branches:
      - main

jobs:
  ROS2:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.0

